
package cse340.menus;


import cse340.menus.ExperimentTrial;

/* ********************************************************************************************** *
 * ********************************************************************************************** *
 *                      DO NOT EDIT THIS FILE, PLEASE, DO NOT EDIT THIS FILE                      *
 * ********************************************************************************************** *
 * ********************************************************************************************** */


public interface TrialListener {
    /** Callback function called when a trial is finished. */
    void onTrialCompleted(ExperimentTrial trial);
}
